#tell travis what to do 
sudo: required
services: #we need a copy of docker
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

  #command to execute to run the suit, if it return other thing but zero, 
  #travis will suppouse that the test suit failed
script:
  - docker run docker-react npm run test -- --coverage