#tell travis what to do 
sudo: required
services: #we need a copy of docker
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

  #command to execute to run the suit, if it return other thing but zero, 
  #travis will suppouse that the test suit failed
script:
  - docker run docker-react npm run test -- --coverage

deploy:
  privider: elasticbeanstalk
  region: ""us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-355467072701"     #hard drive in AWS where travis upload it
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
